package bean;

// Generated 2013-1-31 22:24:10 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * BuoyLast2 generated by hbm2java
 */
public class BuoyLast2 implements java.io.Serializable {

	private BuoyLast2Id id;
	private BigDecimal yxbg;
	private BigDecimal pjbg;
	private BigDecimal qw;
	private BigDecimal qy;
	private BigDecimal bcsw;
	private BigDecimal zdbg;
	private BigDecimal fs;
	private BigDecimal fx;
	private BigDecimal yxbzw;

	public BuoyLast2() {
	}

	public BuoyLast2(BuoyLast2Id id) {
		this.id = id;
	}

	public BuoyLast2(BuoyLast2Id id, BigDecimal yxbg, BigDecimal pjbg,
			BigDecimal qw, BigDecimal qy, BigDecimal bcsw, BigDecimal zdbg,
			BigDecimal fs, BigDecimal fx, BigDecimal yxbzw) {
		this.id = id;
		this.yxbg = yxbg;
		this.pjbg = pjbg;
		this.qw = qw;
		this.qy = qy;
		this.bcsw = bcsw;
		this.zdbg = zdbg;
		this.fs = fs;
		this.fx = fx;
		this.yxbzw = yxbzw;
	}

	public BuoyLast2Id getId() {
		return this.id;
	}

	public void setId(BuoyLast2Id id) {
		this.id = id;
	}

	public BigDecimal getYxbg() {
		return this.yxbg;
	}

	public void setYxbg(BigDecimal yxbg) {
		this.yxbg = yxbg;
	}

	public BigDecimal getPjbg() {
		return this.pjbg;
	}

	public void setPjbg(BigDecimal pjbg) {
		this.pjbg = pjbg;
	}

	public BigDecimal getQw() {
		return this.qw;
	}

	public void setQw(BigDecimal qw) {
		this.qw = qw;
	}

	public BigDecimal getQy() {
		return this.qy;
	}

	public void setQy(BigDecimal qy) {
		this.qy = qy;
	}

	public BigDecimal getBcsw() {
		return this.bcsw;
	}

	public void setBcsw(BigDecimal bcsw) {
		this.bcsw = bcsw;
	}

	public BigDecimal getZdbg() {
		return this.zdbg;
	}

	public void setZdbg(BigDecimal zdbg) {
		this.zdbg = zdbg;
	}

	public BigDecimal getFs() {
		return this.fs;
	}

	public void setFs(BigDecimal fs) {
		this.fs = fs;
	}

	public BigDecimal getFx() {
		return this.fx;
	}

	public void setFx(BigDecimal fx) {
		this.fx = fx;
	}

	public BigDecimal getYxbzw() {
		return this.yxbzw;
	}

	public void setYxbzw(BigDecimal yxbzw) {
		this.yxbzw = yxbzw;
	}

}
