package bean;

// Generated 2012-11-25 16:18:31 by Hibernate Tools 3.4.0.CR1

/**
 * HqtqybId generated by hbm2java
 */
public class HqtqybId implements java.io.Serializable {

	private long ybtc;
	private long hqbh;

	public HqtqybId() {
	}

	public HqtqybId(long ybtc, long hqbh) {
		this.ybtc = ybtc;
		this.hqbh = hqbh;
	}

	public long getYbtc() {
		return this.ybtc;
	}

	public void setYbtc(long ybtc) {
		this.ybtc = ybtc;
	}

	public long getHqbh() {
		return this.hqbh;
	}

	public void setHqbh(long hqbh) {
		this.hqbh = hqbh;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HqtqybId))
			return false;
		HqtqybId castOther = (HqtqybId) other;

		return (this.getYbtc() == castOther.getYbtc())
				&& (this.getHqbh() == castOther.getHqbh());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getYbtc();
		result = 37 * result + (int) this.getHqbh();
		return result;
	}

}
