package bean;

// Generated 2013-1-29 16:25:24 by Hibernate Tools 3.4.0.CR1

/**
 * Hqybd generated by hbm2java
 */
public class Hqybd implements java.io.Serializable {

	private HqybdId id;

	public Hqybd() {
	}

	public Hqybd(HqybdId id) {
		this.id = id;
	}

	public HqybdId getId() {
		return this.id;
	}

	public void setId(HqybdId id) {
		this.id = id;
	}

}
