package bean;

// Generated 2013-3-8 16:06:26 by Hibernate Tools 3.4.0.CR1

/**
 * JcfwxxId generated by hbm2java
 */
public class JcfwxxId implements java.io.Serializable {

	private String period;
	private String filename;

	public JcfwxxId() {
	}

	public JcfwxxId(String period, String filename) {
		this.period = period;
		this.filename = filename;
	}

	public String getPeriod() {
		return this.period;
	}

	public void setPeriod(String period) {
		this.period = period;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof JcfwxxId))
			return false;
		JcfwxxId castOther = (JcfwxxId) other;

		return ((this.getPeriod() == castOther.getPeriod()) || (this
				.getPeriod() != null && castOther.getPeriod() != null && this
				.getPeriod().equals(castOther.getPeriod())))
				&& ((this.getFilename() == castOther.getFilename()) || (this
						.getFilename() != null
						&& castOther.getFilename() != null && this
						.getFilename().equals(castOther.getFilename())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPeriod() == null ? 0 : this.getPeriod().hashCode());
		result = 37 * result
				+ (getFilename() == null ? 0 : this.getFilename().hashCode());
		return result;
	}

}
