package bean;

// Generated 2013-3-8 16:06:26 by Hibernate Tools 3.4.0.CR1

/**
 * Jcfwxx generated by hbm2java
 */
public class Jcfwxx implements java.io.Serializable {

	private JcfwxxId id;

	public Jcfwxx() {
	}

	public Jcfwxx(JcfwxxId id) {
		this.id = id;
	}

	public JcfwxxId getId() {
		return this.id;
	}

	public void setId(JcfwxxId id) {
		this.id = id;
	}

}
