package bean;

// Generated 2013-3-8 16:06:26 by Hibernate Tools 3.4.0.CR1

/**
 * TfybdId generated by hbm2java
 */
public class TfybdId implements java.io.Serializable {

	private Long typhNum;
	private String filename;
	private Short releaseNum;
	private String dateTime;

	public TfybdId() {
	}

	public TfybdId(Long typhNum, String filename, Short releaseNum,
			String dateTime) {
		this.typhNum = typhNum;
		this.filename = filename;
		this.releaseNum = releaseNum;
		this.dateTime = dateTime;
	}

	public Long getTyphNum() {
		return this.typhNum;
	}

	public void setTyphNum(Long typhNum) {
		this.typhNum = typhNum;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public Short getReleaseNum() {
		return this.releaseNum;
	}

	public void setReleaseNum(Short releaseNum) {
		this.releaseNum = releaseNum;
	}

	public String getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(String dateTime) {
		this.dateTime = dateTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TfybdId))
			return false;
		TfybdId castOther = (TfybdId) other;

		return ((this.getTyphNum() == castOther.getTyphNum()) || (this
				.getTyphNum() != null && castOther.getTyphNum() != null && this
				.getTyphNum().equals(castOther.getTyphNum())))
				&& ((this.getFilename() == castOther.getFilename()) || (this
						.getFilename() != null
						&& castOther.getFilename() != null && this
						.getFilename().equals(castOther.getFilename())))
				&& ((this.getReleaseNum() == castOther.getReleaseNum()) || (this
						.getReleaseNum() != null
						&& castOther.getReleaseNum() != null && this
						.getReleaseNum().equals(castOther.getReleaseNum())))
				&& ((this.getDateTime() == castOther.getDateTime()) || (this
						.getDateTime() != null
						&& castOther.getDateTime() != null && this
						.getDateTime().equals(castOther.getDateTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTyphNum() == null ? 0 : this.getTyphNum().hashCode());
		result = 37 * result
				+ (getFilename() == null ? 0 : this.getFilename().hashCode());
		result = 37
				* result
				+ (getReleaseNum() == null ? 0 : this.getReleaseNum()
						.hashCode());
		result = 37 * result
				+ (getDateTime() == null ? 0 : this.getDateTime().hashCode());
		return result;
	}

}
