package bean;

// Generated 2013-3-8 16:06:26 by Hibernate Tools 3.4.0.CR1

/**
 * Tfybd generated by hbm2java
 */
public class Tfybd implements java.io.Serializable {

	private TfybdId id;

	public Tfybd() {
	}

	public Tfybd(TfybdId id) {
		this.id = id;
	}

	public TfybdId getId() {
		return this.id;
	}

	public void setId(TfybdId id) {
		this.id = id;
	}

}
