package bean;

// Generated 2013-1-18 14:26:33 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TyphMonitorId generated by hbm2java
 */
public class TyphMonitorId implements java.io.Serializable {

	private long typhNum;
	private Date routeTime;

	public TyphMonitorId() {
	}

	public TyphMonitorId(long typhNum, Date routeTime) {
		this.typhNum = typhNum;
		this.routeTime = routeTime;
	}

	public long getTyphNum() {
		return this.typhNum;
	}

	public void setTyphNum(long typhNum) {
		this.typhNum = typhNum;
	}

	public Date getRouteTime() {
		return this.routeTime;
	}

	public void setRouteTime(Date routeTime) {
		this.routeTime = routeTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TyphMonitorId))
			return false;
		TyphMonitorId castOther = (TyphMonitorId) other;

		return (this.getTyphNum() == castOther.getTyphNum())
				&& ((this.getRouteTime() == castOther.getRouteTime()) || (this
						.getRouteTime() != null
						&& castOther.getRouteTime() != null && this
						.getRouteTime().equals(castOther.getRouteTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getTyphNum();
		result = 37 * result
				+ (getRouteTime() == null ? 0 : this.getRouteTime().hashCode());
		return result;
	}

}
