package bean;

// Generated 2012-12-25 21:13:37 by Hibernate Tools 3.4.0.CR1

/**
 * TyphInfo generated by hbm2java
 */
public class TyphInfo implements java.io.Serializable {

	private long typhNum;
	private String chName;
	private String enName;
	private boolean isongoing;
	
	public TyphInfo() {
	}

	public TyphInfo(long typhNum) {
		this.typhNum = typhNum;
	}

	public TyphInfo(long typhNum, String chName, String enName, boolean isongoing) {
		this.typhNum = typhNum;
		this.chName = chName;
		this.enName = enName;
		this.isongoing = isongoing;
	}

	public long getTyphNum() {
		return this.typhNum;
	}

	public void setTyphNum(long typhNum) {
		this.typhNum = typhNum;
	}

	public String getChName() {
		return this.chName;
	}

	public void setChName(String chName) {
		this.chName = chName;
	}

	public String getEnName() {
		return this.enName;
	}

	public void setEnName(String enName) {
		this.enName = enName;
	}

	public boolean getIsongoing() {
		return this.isongoing;
	}
	
	public void setIsongoing(boolean isongoing) {
		this.isongoing = isongoing;
	}
}
