package bean;

// Generated 2012-11-25 21:12:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Zfhy generated by hbm2java
 */
public class Zfhy implements java.io.Serializable {

	private ZfhyId id;
	private Date qbsj;
	private String tqqk;
	private String fx;
	private String fs;
	private String scfw;
	private String fl;
	private String yl;

	public Zfhy() {
	}

	public Zfhy(ZfhyId id, Date qbsj) {
		this.id = id;
		this.qbsj = qbsj;
	}

	public Zfhy(ZfhyId id, Date qbsj, String tqqk, String fx, String fs,
			String scfw, String fl, String yl) {
		this.id = id;
		this.qbsj = qbsj;
		this.tqqk = tqqk;
		this.fx = fx;
		this.fs = fs;
		this.scfw = scfw;
		this.fl = fl;
		this.yl = yl;
	}

	public ZfhyId getId() {
		return this.id;
	}

	public void setId(ZfhyId id) {
		this.id = id;
	}

	public Date getQbsj() {
		return this.qbsj;
	}

	public void setQbsj(Date qbsj) {
		this.qbsj = qbsj;
	}

	public String getTqqk() {
		return this.tqqk;
	}

	public void setTqqk(String tqqk) {
		this.tqqk = tqqk;
	}

	public String getFx() {
		return this.fx;
	}

	public void setFx(String fx) {
		this.fx = fx;
	}

	public String getFs() {
		return this.fs;
	}

	public void setFs(String fs) {
		this.fs = fs;
	}

	public String getScfw() {
		return this.scfw;
	}

	public void setScfw(String scfw) {
		this.scfw = scfw;
	}

	public String getFl() {
		return this.fl;
	}

	public void setFl(String fl) {
		this.fl = fl;
	}

	public String getYl() {
		return this.yl;
	}

	public void setYl(String yl) {
		this.yl = yl;
	}

}
