package bean;

// Generated 2012-11-25 21:12:47 by Hibernate Tools 3.4.0.CR1

/**
 * ZfhyId generated by hbm2java
 */
public class ZfhyId implements java.io.Serializable {

	private String hymc;
	private long ybtc;

	public ZfhyId() {
	}

	public ZfhyId(String hymc, long ybtc) {
		this.hymc = hymc;
		this.ybtc = ybtc;
	}

	public String getHymc() {
		return this.hymc;
	}

	public void setHymc(String hymc) {
		this.hymc = hymc;
	}

	public long getYbtc() {
		return this.ybtc;
	}

	public void setYbtc(long ybtc) {
		this.ybtc = ybtc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ZfhyId))
			return false;
		ZfhyId castOther = (ZfhyId) other;

		return ((this.getHymc() == castOther.getHymc()) || (this.getHymc() != null
				&& castOther.getHymc() != null && this.getHymc().equals(
				castOther.getHymc())))
				&& (this.getYbtc() == castOther.getYbtc());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getHymc() == null ? 0 : this.getHymc().hashCode());
		result = 37 * result + (int) this.getYbtc();
		return result;
	}

}
