package bean;

// Generated 2013-1-29 16:25:24 by Hibernate Tools 3.4.0.CR1

/**
 * Zfybd generated by hbm2java
 */
public class Zfybd implements java.io.Serializable {

	private ZfybdId id;

	public Zfybd() {
	}

	public Zfybd(ZfybdId id) {
		this.id = id;
	}

	public ZfybdId getId() {
		return this.id;
	}

	public void setId(ZfybdId id) {
		this.id = id;
	}

}
