package bean;

// Generated 2013-5-5 13:44:40 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ArgoProfile generated by hbm2java
 */
public class ArgoProfile implements java.io.Serializable {

	private ArgoProfileId id;
	private String projectName;
	private String piName;
	private String direction;
	private String dataCentre;
	private Date dateCreation;
	private Date dateUpdate;
	private String dcReference;
	private String dataStateIndicator;
	private String instReference;
	private String wmoInstType;
	private BigDecimal juld;
	private Short juldQc;
	private BigDecimal juldLocation;
	private BigDecimal latitude;
	private BigDecimal longitude;

	public ArgoProfile() {
	}

	public ArgoProfile(ArgoProfileId id) {
		this.id = id;
	}

	public ArgoProfile(ArgoProfileId id, String projectName, String piName,
			String direction, String dataCentre, Date dateCreation,
			Date dateUpdate, String dcReference, String dataStateIndicator,
			String instReference, String wmoInstType, BigDecimal juld,
			Short juldQc, BigDecimal juldLocation, BigDecimal latitude,
			BigDecimal longitude) {
		this.id = id;
		this.projectName = projectName;
		this.piName = piName;
		this.direction = direction;
		this.dataCentre = dataCentre;
		this.dateCreation = dateCreation;
		this.dateUpdate = dateUpdate;
		this.dcReference = dcReference;
		this.dataStateIndicator = dataStateIndicator;
		this.instReference = instReference;
		this.wmoInstType = wmoInstType;
		this.juld = juld;
		this.juldQc = juldQc;
		this.juldLocation = juldLocation;
		this.latitude = latitude;
		this.longitude = longitude;
	}

	public ArgoProfileId getId() {
		return this.id;
	}

	public void setId(ArgoProfileId id) {
		this.id = id;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getPiName() {
		return this.piName;
	}

	public void setPiName(String piName) {
		this.piName = piName;
	}

	public String getDirection() {
		return this.direction;
	}

	public void setDirection(String direction) {
		this.direction = direction;
	}

	public String getDataCentre() {
		return this.dataCentre;
	}

	public void setDataCentre(String dataCentre) {
		this.dataCentre = dataCentre;
	}

	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	public Date getDateUpdate() {
		return this.dateUpdate;
	}

	public void setDateUpdate(Date dateUpdate) {
		this.dateUpdate = dateUpdate;
	}

	public String getDcReference() {
		return this.dcReference;
	}

	public void setDcReference(String dcReference) {
		this.dcReference = dcReference;
	}

	public String getDataStateIndicator() {
		return this.dataStateIndicator;
	}

	public void setDataStateIndicator(String dataStateIndicator) {
		this.dataStateIndicator = dataStateIndicator;
	}

	public String getInstReference() {
		return this.instReference;
	}

	public void setInstReference(String instReference) {
		this.instReference = instReference;
	}

	public String getWmoInstType() {
		return this.wmoInstType;
	}

	public void setWmoInstType(String wmoInstType) {
		this.wmoInstType = wmoInstType;
	}

	public BigDecimal getJuld() {
		return this.juld;
	}

	public void setJuld(BigDecimal juld) {
		this.juld = juld;
	}

	public Short getJuldQc() {
		return this.juldQc;
	}

	public void setJuldQc(Short juldQc) {
		this.juldQc = juldQc;
	}

	public BigDecimal getJuldLocation() {
		return this.juldLocation;
	}

	public void setJuldLocation(BigDecimal juldLocation) {
		this.juldLocation = juldLocation;
	}

	public BigDecimal getLatitude() {
		return this.latitude;
	}

	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	public BigDecimal getLongitude() {
		return this.longitude;
	}

	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

}
