package bean;

// Generated 2013-5-5 13:44:40 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * ArgoProfileSlice generated by hbm2java
 */
public class ArgoProfileSlice implements java.io.Serializable {

	private ArgoProfileSliceId id;
	private BigDecimal pres;
	private BigDecimal presAdjusted;
	private Short presAdjustedQc;
	private BigDecimal presAdjustedError;
	private BigDecimal temp;
	private BigDecimal tempAdjusted;
	private Short tempAdjustedQc;
	private BigDecimal tempAdjustedError;
	private BigDecimal psal;
	private BigDecimal psalAdjusted;
	private Short psalAdjustedQc;
	private BigDecimal psalAdjustedError;
	private Short presQc;
	private Short tempQc;
	private Short psalQc;

	public ArgoProfileSlice() {
	}

	public ArgoProfileSlice(ArgoProfileSliceId id) {
		this.id = id;
	}

	public ArgoProfileSlice(ArgoProfileSliceId id, BigDecimal pres,
			BigDecimal presAdjusted, Short presAdjustedQc,
			BigDecimal presAdjustedError, BigDecimal temp,
			BigDecimal tempAdjusted, Short tempAdjustedQc,
			BigDecimal tempAdjustedError, BigDecimal psal,
			BigDecimal psalAdjusted, Short psalAdjustedQc,
			BigDecimal psalAdjustedError, Short presQc, Short tempQc,
			Short psalQc) {
		this.id = id;
		this.pres = pres;
		this.presAdjusted = presAdjusted;
		this.presAdjustedQc = presAdjustedQc;
		this.presAdjustedError = presAdjustedError;
		this.temp = temp;
		this.tempAdjusted = tempAdjusted;
		this.tempAdjustedQc = tempAdjustedQc;
		this.tempAdjustedError = tempAdjustedError;
		this.psal = psal;
		this.psalAdjusted = psalAdjusted;
		this.psalAdjustedQc = psalAdjustedQc;
		this.psalAdjustedError = psalAdjustedError;
		this.presQc = presQc;
		this.tempQc = tempQc;
		this.psalQc = psalQc;
	}

	public ArgoProfileSliceId getId() {
		return this.id;
	}

	public void setId(ArgoProfileSliceId id) {
		this.id = id;
	}

	public BigDecimal getPres() {
		return this.pres;
	}

	public void setPres(BigDecimal pres) {
		this.pres = pres;
	}

	public BigDecimal getPresAdjusted() {
		return this.presAdjusted;
	}

	public void setPresAdjusted(BigDecimal presAdjusted) {
		this.presAdjusted = presAdjusted;
	}

	public Short getPresAdjustedQc() {
		return this.presAdjustedQc;
	}

	public void setPresAdjustedQc(Short presAdjustedQc) {
		this.presAdjustedQc = presAdjustedQc;
	}

	public BigDecimal getPresAdjustedError() {
		return this.presAdjustedError;
	}

	public void setPresAdjustedError(BigDecimal presAdjustedError) {
		this.presAdjustedError = presAdjustedError;
	}

	public BigDecimal getTemp() {
		return this.temp;
	}

	public void setTemp(BigDecimal temp) {
		this.temp = temp;
	}

	public BigDecimal getTempAdjusted() {
		return this.tempAdjusted;
	}

	public void setTempAdjusted(BigDecimal tempAdjusted) {
		this.tempAdjusted = tempAdjusted;
	}

	public Short getTempAdjustedQc() {
		return this.tempAdjustedQc;
	}

	public void setTempAdjustedQc(Short tempAdjustedQc) {
		this.tempAdjustedQc = tempAdjustedQc;
	}

	public BigDecimal getTempAdjustedError() {
		return this.tempAdjustedError;
	}

	public void setTempAdjustedError(BigDecimal tempAdjustedError) {
		this.tempAdjustedError = tempAdjustedError;
	}

	public BigDecimal getPsal() {
		return this.psal;
	}

	public void setPsal(BigDecimal psal) {
		this.psal = psal;
	}

	public BigDecimal getPsalAdjusted() {
		return this.psalAdjusted;
	}

	public void setPsalAdjusted(BigDecimal psalAdjusted) {
		this.psalAdjusted = psalAdjusted;
	}

	public Short getPsalAdjustedQc() {
		return this.psalAdjustedQc;
	}

	public void setPsalAdjustedQc(Short psalAdjustedQc) {
		this.psalAdjustedQc = psalAdjustedQc;
	}

	public BigDecimal getPsalAdjustedError() {
		return this.psalAdjustedError;
	}

	public void setPsalAdjustedError(BigDecimal psalAdjustedError) {
		this.psalAdjustedError = psalAdjustedError;
	}

	public Short getPresQc() {
		return this.presQc;
	}

	public void setPresQc(Short presQc) {
		this.presQc = presQc;
	}

	public Short getTempQc() {
		return this.tempQc;
	}

	public void setTempQc(Short tempQc) {
		this.tempQc = tempQc;
	}

	public Short getPsalQc() {
		return this.psalQc;
	}

	public void setPsalQc(Short psalQc) {
		this.psalQc = psalQc;
	}

}
