package bean;

// Generated 2013-5-5 13:44:40 by Hibernate Tools 3.4.0.CR1

/**
 * ArgoProfileId generated by hbm2java
 */
public class ArgoProfileId implements java.io.Serializable {

	private String platformNumber;
	private String cycleNumber;
	private String dataMode;

	public ArgoProfileId() {
	}

	public ArgoProfileId(String platformNumber, String cycleNumber,
			String dataMode) {
		this.platformNumber = platformNumber;
		this.cycleNumber = cycleNumber;
		this.dataMode = dataMode;
	}

	public String getPlatformNumber() {
		return this.platformNumber;
	}

	public void setPlatformNumber(String platformNumber) {
		this.platformNumber = platformNumber;
	}

	public String getCycleNumber() {
		return this.cycleNumber;
	}

	public void setCycleNumber(String cycleNumber) {
		this.cycleNumber = cycleNumber;
	}

	public String getDataMode() {
		return this.dataMode;
	}

	public void setDataMode(String dataMode) {
		this.dataMode = dataMode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArgoProfileId))
			return false;
		ArgoProfileId castOther = (ArgoProfileId) other;

		return ((this.getPlatformNumber() == castOther.getPlatformNumber()) || (this
				.getPlatformNumber() != null
				&& castOther.getPlatformNumber() != null && this
				.getPlatformNumber().equals(castOther.getPlatformNumber())))
				&& ((this.getCycleNumber() == castOther.getCycleNumber()) || (this
						.getCycleNumber() != null
						&& castOther.getCycleNumber() != null && this
						.getCycleNumber().equals(castOther.getCycleNumber())))
				&& ((this.getDataMode() == castOther.getDataMode()) || (this
						.getDataMode() != null
						&& castOther.getDataMode() != null && this
						.getDataMode().equals(castOther.getDataMode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPlatformNumber() == null ? 0 : this.getPlatformNumber()
						.hashCode());
		result = 37
				* result
				+ (getCycleNumber() == null ? 0 : this.getCycleNumber()
						.hashCode());
		result = 37 * result
				+ (getDataMode() == null ? 0 : this.getDataMode().hashCode());
		return result;
	}

}
