package bean;

// Generated 2013-5-10 16:12:56 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ArgoMetaInfo generated by hbm2java
 */
public class ArgoMetaInfo implements java.io.Serializable {

	private String platformNumber;
	private String ptt;
	private String transSystem;
	private BigDecimal transRepetition;
	private String positioningSystem;
	private String platformModel;
	private String platformMaker;
	private String direction;
	private String projectName;
	private String piName;
	private Date launchDate;
	private BigDecimal launchLatitude;
	private BigDecimal launchLongitude;
	private Date startDate;
	private String deployPlatform;
	private String sensor;
	private String sensorMaker;
	private String sensorModel;
	private String sensorSerialNo;
	private String sensorUnits;
	private String sensorAccuracy;
	private String sensorResolution;
	private String repetitionRate;
	private String cycleTime;
	private String parkingTime;
	private String descendingProfilingTime;
	private String ascendingProfilingTime;
	private String surfaceTime;
	private String parkingPressure;
	private String deepestPressure;

	public ArgoMetaInfo() {
	}

	public ArgoMetaInfo(String platformNumber) {
		this.platformNumber = platformNumber;
	}

	public ArgoMetaInfo(String platformNumber, String ptt, String transSystem,
			BigDecimal transRepetition, String positioningSystem,
			String platformModel, String platformMaker, String direction,
			String projectName, String piName, Date launchDate,
			BigDecimal launchLatitude, BigDecimal launchLongitude,
			Date startDate, String deployPlatform, String sensor,
			String sensorMaker, String sensorModel, String sensorSerialNo,
			String sensorUnits, String sensorAccuracy, String sensorResolution,
			String repetitionRate, String cycleTime, String parkingTime,
			String descendingProfilingTime, String ascendingProfilingTime,
			String surfaceTime, String parkingPressure, String deepestPressure) {
		this.platformNumber = platformNumber;
		this.ptt = ptt;
		this.transSystem = transSystem;
		this.transRepetition = transRepetition;
		this.positioningSystem = positioningSystem;
		this.platformModel = platformModel;
		this.platformMaker = platformMaker;
		this.direction = direction;
		this.projectName = projectName;
		this.piName = piName;
		this.launchDate = launchDate;
		this.launchLatitude = launchLatitude;
		this.launchLongitude = launchLongitude;
		this.startDate = startDate;
		this.deployPlatform = deployPlatform;
		this.sensor = sensor;
		this.sensorMaker = sensorMaker;
		this.sensorModel = sensorModel;
		this.sensorSerialNo = sensorSerialNo;
		this.sensorUnits = sensorUnits;
		this.sensorAccuracy = sensorAccuracy;
		this.sensorResolution = sensorResolution;
		this.repetitionRate = repetitionRate;
		this.cycleTime = cycleTime;
		this.parkingTime = parkingTime;
		this.descendingProfilingTime = descendingProfilingTime;
		this.ascendingProfilingTime = ascendingProfilingTime;
		this.surfaceTime = surfaceTime;
		this.parkingPressure = parkingPressure;
		this.deepestPressure = deepestPressure;
	}

	public String getPlatformNumber() {
		return this.platformNumber;
	}

	public void setPlatformNumber(String platformNumber) {
		this.platformNumber = platformNumber;
	}

	public String getPtt() {
		return this.ptt;
	}

	public void setPtt(String ptt) {
		this.ptt = ptt;
	}

	public String getTransSystem() {
		return this.transSystem;
	}

	public void setTransSystem(String transSystem) {
		this.transSystem = transSystem;
	}

	public BigDecimal getTransRepetition() {
		return this.transRepetition;
	}

	public void setTransRepetition(BigDecimal transRepetition) {
		this.transRepetition = transRepetition;
	}

	public String getPositioningSystem() {
		return this.positioningSystem;
	}

	public void setPositioningSystem(String positioningSystem) {
		this.positioningSystem = positioningSystem;
	}

	public String getPlatformModel() {
		return this.platformModel;
	}

	public void setPlatformModel(String platformModel) {
		this.platformModel = platformModel;
	}

	public String getPlatformMaker() {
		return this.platformMaker;
	}

	public void setPlatformMaker(String platformMaker) {
		this.platformMaker = platformMaker;
	}

	public String getDirection() {
		return this.direction;
	}

	public void setDirection(String direction) {
		this.direction = direction;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getPiName() {
		return this.piName;
	}

	public void setPiName(String piName) {
		this.piName = piName;
	}

	public Date getLaunchDate() {
		return this.launchDate;
	}

	public void setLaunchDate(Date launchDate) {
		this.launchDate = launchDate;
	}

	public BigDecimal getLaunchLatitude() {
		return this.launchLatitude;
	}

	public void setLaunchLatitude(BigDecimal launchLatitude) {
		this.launchLatitude = launchLatitude;
	}

	public BigDecimal getLaunchLongitude() {
		return this.launchLongitude;
	}

	public void setLaunchLongitude(BigDecimal launchLongitude) {
		this.launchLongitude = launchLongitude;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public String getDeployPlatform() {
		return this.deployPlatform;
	}

	public void setDeployPlatform(String deployPlatform) {
		this.deployPlatform = deployPlatform;
	}

	public String getSensor() {
		return this.sensor;
	}

	public void setSensor(String sensor) {
		this.sensor = sensor;
	}

	public String getSensorMaker() {
		return this.sensorMaker;
	}

	public void setSensorMaker(String sensorMaker) {
		this.sensorMaker = sensorMaker;
	}

	public String getSensorModel() {
		return this.sensorModel;
	}

	public void setSensorModel(String sensorModel) {
		this.sensorModel = sensorModel;
	}

	public String getSensorSerialNo() {
		return this.sensorSerialNo;
	}

	public void setSensorSerialNo(String sensorSerialNo) {
		this.sensorSerialNo = sensorSerialNo;
	}

	public String getSensorUnits() {
		return this.sensorUnits;
	}

	public void setSensorUnits(String sensorUnits) {
		this.sensorUnits = sensorUnits;
	}

	public String getSensorAccuracy() {
		return this.sensorAccuracy;
	}

	public void setSensorAccuracy(String sensorAccuracy) {
		this.sensorAccuracy = sensorAccuracy;
	}

	public String getSensorResolution() {
		return this.sensorResolution;
	}

	public void setSensorResolution(String sensorResolution) {
		this.sensorResolution = sensorResolution;
	}

	public String getRepetitionRate() {
		return this.repetitionRate;
	}

	public void setRepetitionRate(String repetitionRate) {
		this.repetitionRate = repetitionRate;
	}

	public String getCycleTime() {
		return this.cycleTime;
	}

	public void setCycleTime(String cycleTime) {
		this.cycleTime = cycleTime;
	}

	public String getParkingTime() {
		return this.parkingTime;
	}

	public void setParkingTime(String parkingTime) {
		this.parkingTime = parkingTime;
	}

	public String getDescendingProfilingTime() {
		return this.descendingProfilingTime;
	}

	public void setDescendingProfilingTime(String descendingProfilingTime) {
		this.descendingProfilingTime = descendingProfilingTime;
	}

	public String getAscendingProfilingTime() {
		return this.ascendingProfilingTime;
	}

	public void setAscendingProfilingTime(String ascendingProfilingTime) {
		this.ascendingProfilingTime = ascendingProfilingTime;
	}

	public String getSurfaceTime() {
		return this.surfaceTime;
	}

	public void setSurfaceTime(String surfaceTime) {
		this.surfaceTime = surfaceTime;
	}

	public String getParkingPressure() {
		return this.parkingPressure;
	}

	public void setParkingPressure(String parkingPressure) {
		this.parkingPressure = parkingPressure;
	}

	public String getDeepestPressure() {
		return this.deepestPressure;
	}

	public void setDeepestPressure(String deepestPressure) {
		this.deepestPressure = deepestPressure;
	}

}
