package bean;

// Generated 2013-5-5 13:44:40 by Hibernate Tools 3.4.0.CR1

/**
 * ArgoProfileSliceId generated by hbm2java
 */
public class ArgoProfileSliceId implements java.io.Serializable {

	private String platformNumber;
	private String cycleNumber;
	private short moveNum;

	public ArgoProfileSliceId() {
	}

	public ArgoProfileSliceId(String platformNumber, String cycleNumber,
			short moveNum) {
		this.platformNumber = platformNumber;
		this.cycleNumber = cycleNumber;
		this.moveNum = moveNum;
	}

	public String getPlatformNumber() {
		return this.platformNumber;
	}

	public void setPlatformNumber(String platformNumber) {
		this.platformNumber = platformNumber;
	}

	public String getCycleNumber() {
		return this.cycleNumber;
	}

	public void setCycleNumber(String cycleNumber) {
		this.cycleNumber = cycleNumber;
	}

	public short getMoveNum() {
		return this.moveNum;
	}

	public void setMoveNum(short moveNum) {
		this.moveNum = moveNum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArgoProfileSliceId))
			return false;
		ArgoProfileSliceId castOther = (ArgoProfileSliceId) other;

		return ((this.getPlatformNumber() == castOther.getPlatformNumber()) || (this
				.getPlatformNumber() != null
				&& castOther.getPlatformNumber() != null && this
				.getPlatformNumber().equals(castOther.getPlatformNumber())))
				&& ((this.getCycleNumber() == castOther.getCycleNumber()) || (this
						.getCycleNumber() != null
						&& castOther.getCycleNumber() != null && this
						.getCycleNumber().equals(castOther.getCycleNumber())))
				&& (this.getMoveNum() == castOther.getMoveNum());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPlatformNumber() == null ? 0 : this.getPlatformNumber()
						.hashCode());
		result = 37
				* result
				+ (getCycleNumber() == null ? 0 : this.getCycleNumber()
						.hashCode());
		result = 37 * result + this.getMoveNum();
		return result;
	}

}
