package bean;

// Generated 2013-5-18 17:43:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * FxzdWtzInfoId generated by hbm2java
 */
public class FxzdWtzInfoId implements java.io.Serializable {

	private int WNumber;
	private Date occurDate;

	public FxzdWtzInfoId() {
	}

	public FxzdWtzInfoId(int WNumber, Date occurDate) {
		this.WNumber = WNumber;
		this.occurDate = occurDate;
	}

	public int getWNumber() {
		return this.WNumber;
	}

	public void setWNumber(int WNumber) {
		this.WNumber = WNumber;
	}

	public Date getOccurDate() {
		return this.occurDate;
	}

	public void setOccurDate(Date occurDate) {
		this.occurDate = occurDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FxzdWtzInfoId))
			return false;
		FxzdWtzInfoId castOther = (FxzdWtzInfoId) other;

		return (this.getWNumber() == castOther.getWNumber())
				&& ((this.getOccurDate() == castOther.getOccurDate()) || (this
						.getOccurDate() != null
						&& castOther.getOccurDate() != null && this
						.getOccurDate().equals(castOther.getOccurDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getWNumber();
		result = 37 * result
				+ (getOccurDate() == null ? 0 : this.getOccurDate().hashCode());
		return result;
	}

}
