package bean;

// Generated 2012-10-23 21:34:48 by Hibernate Tools 3.4.0.CR1

/**
 * NioVersion generated by hbm2java
 */
public class NioVersion implements java.io.Serializable {

	private String version;

	public NioVersion() {
	}

	public NioVersion(String version) {
		this.version = version;
	}

	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

}
