package bean;

// Generated 2013-4-1 20:56:46 by Hibernate Tools 3.4.0.CR1

/**
 * StationInfoId generated by hbm2java
 */
public class StationInfoId implements java.io.Serializable {

	private String fromdate;
	private String currentdate;
	private String station;

	public StationInfoId() {
	}

	public StationInfoId(String fromdate, String currentdate, String station) {
		this.fromdate = fromdate;
		this.currentdate = currentdate;
		this.station = station;
	}

	public String getFromdate() {
		return this.fromdate;
	}

	public void setFromdate(String fromdate) {
		this.fromdate = fromdate;
	}

	public String getCurrentdate() {
		return this.currentdate;
	}

	public void setCurrentdate(String currentdate) {
		this.currentdate = currentdate;
	}

	public String getStation() {
		return this.station;
	}

	public void setStation(String station) {
		this.station = station;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StationInfoId))
			return false;
		StationInfoId castOther = (StationInfoId) other;

		return ((this.getFromdate() == castOther.getFromdate()) || (this
				.getFromdate() != null && castOther.getFromdate() != null && this
				.getFromdate().equals(castOther.getFromdate())))
				&& ((this.getCurrentdate() == castOther.getCurrentdate()) || (this
						.getCurrentdate() != null
						&& castOther.getCurrentdate() != null && this
						.getCurrentdate().equals(castOther.getCurrentdate())))
				&& ((this.getStation() == castOther.getStation()) || (this
						.getStation() != null && castOther.getStation() != null && this
						.getStation().equals(castOther.getStation())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getFromdate() == null ? 0 : this.getFromdate().hashCode());
		result = 37
				* result
				+ (getCurrentdate() == null ? 0 : this.getCurrentdate()
						.hashCode());
		result = 37 * result
				+ (getStation() == null ? 0 : this.getStation().hashCode());
		return result;
	}

}
