package bean;

// Generated 2013-4-1 20:56:46 by Hibernate Tools 3.4.0.CR1

/**
 * StationInfo generated by hbm2java
 */
public class StationInfo implements java.io.Serializable {

	private StationInfoId id;
	private String qw;
	private String fx;
	private String fs;
	private String njd;

	public StationInfo() {
	}

	public StationInfo(StationInfoId id) {
		this.id = id;
	}

	public StationInfo(StationInfoId id, String qw, String fx, String fs,
			String njd) {
		this.id = id;
		this.qw = qw;
		this.fx = fx;
		this.fs = fs;
		this.njd = njd;
	}

	public StationInfoId getId() {
		return this.id;
	}

	public void setId(StationInfoId id) {
		this.id = id;
	}

	public String getQw() {
		return this.qw;
	}

	public void setQw(String qw) {
		this.qw = qw;
	}

	public String getFx() {
		return this.fx;
	}

	public void setFx(String fx) {
		this.fx = fx;
	}

	public String getFs() {
		return this.fs;
	}

	public void setFs(String fs) {
		this.fs = fs;
	}

	public String getNjd() {
		return this.njd;
	}

	public void setNjd(String njd) {
		this.njd = njd;
	}

}
