package bean;

// Generated 2013-1-18 14:26:33 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TyphForecast generated by hbm2java
 */
public class TyphForecast implements java.io.Serializable {

	private TyphForecastId id;
	private BigDecimal lon;
	private BigDecimal lat;
	private Integer zxfs;
	private BigDecimal radius7;
	private BigDecimal radius10;
	private String strength;

	public TyphForecast() {
	}

	public TyphForecast(TyphForecastId id) {
		this.id = id;
	}

	public TyphForecast(TyphForecastId id, BigDecimal lon, BigDecimal lat,
			Integer zxfs, BigDecimal radius7, BigDecimal radius10, String strength) {
		this.id = id;
		this.lon = lon;
		this.lat = lat;
		this.zxfs = zxfs;
		this.radius7 = radius7;
		this.radius10 = radius10;
		this.strength = strength;
	}

	public TyphForecastId getId() {
		return this.id;
	}

	public void setId(TyphForecastId id) {
		this.id = id;
	}

	public BigDecimal getLon() {
		return this.lon;
	}

	public void setLon(BigDecimal lon) {
		this.lon = lon;
	}

	public BigDecimal getLat() {
		return this.lat;
	}

	public void setLat(BigDecimal lat) {
		this.lat = lat;
	}

	public Integer getZxfs() {
		return this.zxfs;
	}

	public void setZxfs(Integer zxfs) {
		this.zxfs = zxfs;
	}

	public BigDecimal getRadius7() {
		return this.radius7;
	}

	public void setRadius7(BigDecimal radius7) {
		this.radius7 = radius7;
	}

	public BigDecimal getRadius10() {
		return this.radius10;
	}

	public void setRadius10(BigDecimal radius10) {
		this.radius10 = radius10;
	}

	public String getStrength() {
		return this.strength;
	}

	public void setStrength(String strength) {
		this.strength = strength;
	}

}
