package bean;

// Generated 2013-1-18 14:26:33 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TyphMonitor generated by hbm2java
 */
public class TyphMonitor implements java.io.Serializable {

	private TyphMonitorId id;
	private BigDecimal lat;
	private BigDecimal lon;
	private BigDecimal windSpeed;
	private String strength;
	private BigDecimal radius7;
	private BigDecimal radius10;

	public TyphMonitor() {
	}

	public TyphMonitor(TyphMonitorId id) {
		this.id = id;
	}

	public TyphMonitor(TyphMonitorId id, BigDecimal lat, BigDecimal lon,
			BigDecimal windSpeed, String strength, BigDecimal radius7, BigDecimal radius10) {
		this.id = id;
		this.lat = lat;
		this.lon = lon;
		this.windSpeed = windSpeed;
		this.strength = strength;
		this.radius7 = radius7;
		this.radius10 = radius10;
	}

	public TyphMonitorId getId() {
		return this.id;
	}

	public void setId(TyphMonitorId id) {
		this.id = id;
	}

	public BigDecimal getLat() {
		return this.lat;
	}

	public void setLat(BigDecimal lat) {
		this.lat = lat;
	}

	public BigDecimal getLon() {
		return this.lon;
	}

	public void setLon(BigDecimal lon) {
		this.lon = lon;
	}

	public BigDecimal getWindSpeed() {
		return this.windSpeed;
	}

	public void setWindSpeed(BigDecimal windSpeed) {
		this.windSpeed = windSpeed;
	}

	public String getStrength() {
		return this.strength;
	}

	public void setStrength(String strength) {
		this.strength = strength;
	}

	public BigDecimal getRadius7() {
		return this.radius7;
	}

	public void setRadius7(BigDecimal radius7) {
		this.radius7 = radius7;
	}
	
	public BigDecimal getRadius10() {
		return this.radius10;
	}

	public void setRadius10(BigDecimal radius10) {
		this.radius10 = radius10;
	}

}
